//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TicketSalesSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenTau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenTau()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int MaChuyen { get; set; }
        public Nullable<int> MaTau { get; set; }
        public Nullable<int> MaTuyen { get; set; }
        public Nullable<System.DateTime> GioKhoiHanh { get; set; }
        public Nullable<System.DateTime> GioDen { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Tau Tau { get; set; }
        public virtual TuyenDuong TuyenDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
