//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TicketSalesSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ghe()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int MaGhe { get; set; }
        public string SoHieu { get; set; }
        public string ViTri { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaToa { get; set; }
    
        public virtual ToaTau ToaTau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
