//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TicketSalesSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
