//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TicketSalesSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhToan()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int MaThanhToan { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<System.DateTime> ThoiDiem { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
