//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TicketSalesSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToaTau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToaTau()
        {
            this.Ghes = new HashSet<Ghe>();
        }
    
        public int MaToa { get; set; }
        public string TenToa { get; set; }
        public string LoaiGhe { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<int> ViTri { get; set; }
        public Nullable<int> MaTau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ghe> Ghes { get; set; }
        public virtual Tau Tau { get; set; }
    }
}
