//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TicketSalesSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuyenDuong()
        {
            this.ChuyenTaus = new HashSet<ChuyenTau>();
        }
    
        public int MaTuyen { get; set; }
        public Nullable<int> MaGaDi { get; set; }
        public Nullable<int> MaGaDen { get; set; }
        public Nullable<int> KhoangCach { get; set; }
        public Nullable<System.TimeSpan> ThoiGianDuKien { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenTau> ChuyenTaus { get; set; }
        public virtual GaTau GaTau { get; set; }
        public virtual GaTau GaTau1 { get; set; }
    }
}
