//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TicketSalesSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int MaVe { get; set; }
        public Nullable<int> MaHanhKhach { get; set; }
        public Nullable<int> MaChuyen { get; set; }
        public Nullable<int> MaGhe { get; set; }
        public Nullable<int> MaThanhToan { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public string TrangThai { get; set; }
        public string MaQR { get; set; }
    
        public virtual ChuyenTau ChuyenTau { get; set; }
        public virtual Ghe Ghe { get; set; }
        public virtual HanhKhach HanhKhach { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
